<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ResendWP\\Resend\\' => array($vendorDir . '/resend/resend-php/src'),
    'ResendWP\\Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'ResendWP\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'ResendWP\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'ResendWP\\Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'ResendWP\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'ResendWP\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'ResendWP\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
);
