<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '04590e76ac4cfc77b0fa73b47a404f62' => $vendorDir . '/ralouphie/getallheaders/src/getallheaders.php',
    'd2908e1ed551855067a7b099ec0704ff' => $vendorDir . '/symfony/deprecation-contracts/function.php',
    'f9808bbaaf19bcc0cb100c07547eb536' => $vendorDir . '/guzzlehttp/guzzle/src/functions_include.php',
    '7c1469cc85c7999a4b860e37782ada32' => $vendorDir . '/resend/resend-php/src/Resend.php',
);
